### ISSUE TITLE
Conflict with default Runelite UI Overlay behaviour

### ISSUE THREAD

**Issue by MartinNodder** [nwerblun/runelite_linux_custom_cursor#5]
It seems that when your plug in is enabled, and "Also draw system cursor" is disabled, the ability to interact with non-default Runelite UI elements (Map, Chatbox, Inventory) becomes near impossible.

Example: I have the Blast Furnace Plug-In installed. The Blast Furnace UI Overlay displaying the current amount of coal in the blast furnace is displayed in an Infobox (or Infobox group). When I hold my Runelite plug in "Drag Hotkey" (Alt by default), clicking the Infobox results in a purple outline around the Infobox, but is unable to drag and reposition the InfoBox.

I went through nearly all my plug ins, and the only thing that caused it to revert to normal behaviour was disabling the Linux Custom Cursor plug-in.
I then noticed the debug setting and the "Also draw System Cursor" checkbox was disabled. Upon enabling it, the default functionality of the Runelite UI Overlay  returned to normal. Turning it back off resulted in the same "locked" behaviour for non-default Runelite Infoboxes.

My guess is, because you arnt rendering the system cursor (and replacing it with the image overlay), the other overlays are unable to register any movement input, as they are probably listening for System Calls for/from the System Cursor.

**Comment by nwerblun** [comment]
Sorry I was away for a bit. Thanks for bringing this to my attention, I had not had run into this.

Do you have any suggestions for how you think it should behave? I think I can do something like reverting to the default cursor or automatically drawing the cursor + custom image when over some UI element. I'm not sure if there's anything else that's possible.

**Comment by MartinNodder** [comment]
Well the issue is only in relation to moving the UI elements, which is inherent to the base Runelite plug-in itself.

Im not sure if your plug-in can currently interact with another plug-in, but to ensure it has blanket compatibility, you would have to check the base Runelite plug-ins "Drag Hotkey" (typically Alt), store it on your plug in, and then anytime the user presses the corresponding key, temporarily show/use the System cursor while that key is held. 
That might allow the UI element to be interacted with.

**Comment by nwerblun** [comment]
Made it so pressing the drag hotkey will temporarily disable the overlay which should fix this issue. You should see a link to the pull request which will take some time while they review the changes. Whenever it updates to v1.2 in the plugin hub it should be fixed.

Please re-open the issue if it still behaves incorrectly after that.

**Comment by MartinNodder** [comment]
Ill keep you posted once the plug in updates.

Edit: It works when Runelite's UI Drag Key is set to "Alt" but changing the key to something different (like "-") still has the issue.

It should suffice for 99% of users but anyone whose Runelite UI Drag Hotkey is not set to "Alt", will still have issues.
